server:
  port: 8082
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 4096

spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver                                              # 클라이언트 이름
            client-id: ENC(l8HvF1/xCISpDoQWTjyM+yhI9+03S1+syRDScg5CAaM=)    # 클라이언트 ID
            client-secret: ENC(D7rqCq/bMR2q61t+k0UizpHik4Mnoa9s)            # 클라이언트 시크릿
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}' # 로그인 후 리다이렉트 URI
            authorization-grant-type: authorization_code                    # 인증 방식
            scope: name, email                                              # 요청할 사용자 정보 범위
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize     # 사용자 로그인 및 동의 URI
            token-uri: https://nid.naver.com/oauth2.0/token                 # Access Token 요청 URI
            user-info-uri: https://openapi.naver.com/v1/nid/me              # 사용자 정보 조회 URI
            user-name-attribute: response                                   # JSON 응답에서 실제 사용자 정보가 들어있는 키

jwt:
  secret: a-string-secret-at-least-256-bits-long  # 비밀키
  access-token-expiration: 1800000      # 30분(밀리초 단위)
  refresh-token-expiration: 604800000   # 7일(밀리초 단위)
