spring:
  main:
    web-application-type: reactive
  lifecycle:
    timeout-per-shutdown-phase: 30m
  data:
    redis:
      host: 172.27.172.56
      port: 6379
  config:
    import: classpath:app-content.yml,module-grpc.yml

jwt:
  access-token-expiration: 1800000      # 30분(밀리초 단위)
  refresh-token-expiration: 604800000   # 7일(밀리초 단위)

jasypt:
  encryptor:
    bean: jasyptEncryptor

server:
  shutdown: graceful
